services:
  # PostgreSQL Database with pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sop-postgres
    environment:
      POSTGRES_DB: security_ops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Svelte Frontend
  svelte-frontend:
    build: ./svelte-frontend
    container_name: sop-svelte
    environment:
      API_URL: http://localhost:8080
      PYTHON_API_URL: http://localhost:8001
    ports:
      - "3005:3005"
    volumes:
      - ./svelte-frontend:/app
      - /app/node_modules

volumes:
  postgres_data: